#include "codegen.h"
#include <sstream>

namespace greencc {

void CodeGenerator::emit(const std::string& s) {
    output_ += s;
}

void CodeGenerator::emitLine(const std::string& s) {
    emitIndent();
    output_ += s + "\n";
}

void CodeGenerator::emitIndent() {
    for (int i = 0; i < indent_; i++) output_ += "    ";
}

std::string CodeGenerator::generate(Program& program) {
    output_.clear();
    indent_ = 0;
    program.accept(*this);
    return output_;
}

void CodeGenerator::visit(Program& p) {
    
    emitLine("// ═══════════════════════════════════════════════════════");
    emitLine("//  Generated by GreenCC — Energy-Aware C++ Compiler");
    emitLine("//  Optimized for reduced CPU energy consumption");
    emitLine("// ═══════════════════════════════════════════════════════");
    emit("\n");

    
    for (auto& inc : p.includes) {
        emitLine("#include <" + inc + ">");
    }
    if (!p.includes.empty()) emit("\n");

    
    if (p.hasUsing) {
        emitLine("using namespace std;");
        emit("\n");
    }

    
    for (size_t i = 0; i < p.declarations.size(); i++) {
        p.declarations[i]->accept(*this);
        if (i + 1 < p.declarations.size()) emit("\n");
    }
}

void CodeGenerator::visit(FunctionDecl& f) {
    emitIndent();
    emit(f.returnType + " " + f.name + "(");
    for (size_t i = 0; i < f.params.size(); i++) {
        if (i > 0) emit(", ");
        emit(f.params[i].typeName + " " + f.params[i].name);
    }
    emit(") ");
    if (f.body) {
        emit("{\n");
        indent_++;
        for (auto& s : f.body->stmts) {
            s->accept(*this);
        }
        indent_--;
        emitLine("}");
    }
}

void CodeGenerator::visit(Block& s) {
    emitLine("{");
    indent_++;
    for (auto& stmt : s.stmts) {
        stmt->accept(*this);
    }
    indent_--;
    emitLine("}");
}

void CodeGenerator::visit(VarDecl& s) {
    emitIndent();
    if (s.isConst && s.typeName.find("const") == std::string::npos) {
        emit("const ");
    }
    emit(s.typeName + " " + s.name);
    if (s.arraySize > 0) {
        emit("[" + std::to_string(s.arraySize) + "]");
    }
    if (s.init) {
        emit(" = ");
        s.init->accept(*this);
    }
    emit(";\n");
}

void CodeGenerator::visit(ExprStmt& s) {
    emitIndent();
    s.expr->accept(*this);
    emit(";\n");
}

void CodeGenerator::visit(IfStmt& s) {
    emitIndent();
    emit("if (");
    s.condition->accept(*this);
    emit(") ");

    
    if (auto* block = dynamic_cast<Block*>(s.thenBranch.get())) {
        emit("{\n");
        indent_++;
        for (auto& st : block->stmts) st->accept(*this);
        indent_--;
        emitIndent();
        emit("}");
    } else {
        emit("\n");
        indent_++;
        s.thenBranch->accept(*this);
        indent_--;
    }

    if (s.elseBranch) {
        emit(" else ");
        if (auto* block = dynamic_cast<Block*>(s.elseBranch.get())) {
            emit("{\n");
            indent_++;
            for (auto& st : block->stmts) st->accept(*this);
            indent_--;
            emitLine("}");
        } else if (dynamic_cast<IfStmt*>(s.elseBranch.get())) {
            
            s.elseBranch->accept(*this);
        } else {
            emit("\n");
            indent_++;
            s.elseBranch->accept(*this);
            indent_--;
        }
    } else {
        emit("\n");
    }
}

void CodeGenerator::visit(WhileStmt& s) {
    emitIndent();
    emit("while (");
    s.condition->accept(*this);
    emit(") ");
    if (auto* block = dynamic_cast<Block*>(s.body.get())) {
        emit("{\n");
        indent_++;
        for (auto& st : block->stmts) st->accept(*this);
        indent_--;
        emitLine("}");
    } else {
        emit("\n");
        indent_++;
        s.body->accept(*this);
        indent_--;
    }
}

void CodeGenerator::visit(ForStmt& s) {
    emitIndent();
    emit("for (");

    
    if (s.init) {
        if (auto* vd = dynamic_cast<VarDecl*>(s.init.get())) {
            if (vd->isConst && vd->typeName.find("const") == std::string::npos)
                emit("const ");
            emit(vd->typeName + " " + vd->name);
            if (vd->init) { emit(" = "); vd->init->accept(*this); }
        } else if (auto* es = dynamic_cast<ExprStmt*>(s.init.get())) {
            es->expr->accept(*this);
        }
    }
    emit("; ");

    if (s.condition) s.condition->accept(*this);
    emit("; ");

    if (s.update) s.update->accept(*this);
    emit(") ");

    if (auto* block = dynamic_cast<Block*>(s.body.get())) {
        emit("{\n");
        indent_++;
        for (auto& st : block->stmts) st->accept(*this);
        indent_--;
        emitLine("}");
    } else {
        emit("\n");
        indent_++;
        s.body->accept(*this);
        indent_--;
    }
}

void CodeGenerator::visit(ReturnStmt& s) {
    emitIndent();
    emit("return");
    if (s.value) {
        emit(" ");
        s.value->accept(*this);
    }
    emit(";\n");
}

void CodeGenerator::visit(BreakStmt&) {
    emitLine("break;");
}

void CodeGenerator::visit(ContinueStmt&) {
    emitLine("continue;");
}

void CodeGenerator::visit(LiteralExpr& e) {
    emit(e.value);
}

void CodeGenerator::visit(VarExpr& e) {
    emit(e.name);
}

void CodeGenerator::visit(BinaryExpr& e) {
    emit("(");
    e.left->accept(*this);
    emit(" " + std::string(tokenTypeName(e.op)) + " ");
    e.right->accept(*this);
    emit(")");
}

void CodeGenerator::visit(UnaryExpr& e) {
    if (e.prefix) {
        emit(tokenTypeName(e.op));
        e.operand->accept(*this);
    } else {
        e.operand->accept(*this);
        emit(tokenTypeName(e.op));
    }
}

void CodeGenerator::visit(AssignExpr& e) {
    emit(e.target + " " + std::string(tokenTypeName(e.op)) + " ");
    e.value->accept(*this);
}

void CodeGenerator::visit(CallExpr& e) {
    emit(e.callee + "(");
    for (size_t i = 0; i < e.args.size(); i++) {
        if (i > 0) emit(", ");
        e.args[i]->accept(*this);
    }
    emit(")");
}

void CodeGenerator::visit(ArrayAccessExpr& e) {
    emit(e.name + "[");
    e.index->accept(*this);
    emit("]");
}

void CodeGenerator::visit(IOExpr& e) {
    if (e.isOutput) {
        emit("std::cout");
        for (auto& op : e.operands) {
            emit(" << ");
            if (auto* v = dynamic_cast<VarExpr*>(op.get())) {
                if (v->name == "endl") { emit("std::endl"); continue; }
            }
            op->accept(*this);
        }
    } else {
        emit("std::cin");
        for (auto& op : e.operands) {
            emit(" >> ");
            op->accept(*this);
        }
    }
}

} 
